[default]
description = "Default permissions for the plugin"
permissions = ["allow-scan","allow-stop-scan","allow-connect","allow-disconnect","allow-connection-state","allow-send","allow-read","allow-send-string","allow-read-string","allow-subscribe","allow-subscribe-string","allow-unsubscribe","allow-scanning-state"]
